### ISSUE TITLE
dv-border-box-11 支持修改标题文字大小吗？

### ISSUE THREAD

**Issue by nodepade** [vaemusic/datav-vue3#5]
默认的文字大小偏小，最好可以有一个参数允许修改文字大小
[https://s1.ax1x.com/2022/07/24/jjZfg0.png](https://s1.ax1x.com/2022/07/24/jjZfg0.png)

**Comment by vaemusic** [comment]
目前没有提供相对应的配置。不过文字是在一个 class 为 **`dv-border-box-11-title`** 的text元素内，可以在 `style` 里通过 **`:deep()`** 修改 **`.dv-border-box-11-title`** 样式来改变文字的大小。
```css
:deep(.dv-border-box-11-title) {
  font-size: 20px;
}
```
